### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Deploy On Moonbase Alpha Using Truffle

### ISSUE THREAD

**Issue by albertov19** [harodggg/polkadot-hackthon#1]
Hi harodggg,

Thanks for your submission! Unfortunately, I can't read the migrations contract owner. Did you deploy the contracts in Moonbase Alpha our TestNet?

Regards
Alberto

**Comment by harodggg** [comment]
Glad to receive your reminder, I have resubmitted。This is my github:

https://github.com/harodggg/polkadot-hackthon/blob/main/deploy-erc20-moonbeam/READED.md

[image: deploy_erc20.png]

please check again, thank you😘😘



albertov19 <notifications@github.com> 于2020年10月23日周五 下午7:17写道：

**Comment by albertov19** [comment]
Hi harodggg,

I can see that these contracts were submitted to Moonbase Alpha. The issue is that you need to provide the Migrations contract address. You are submitting the account from which the ERC20 was deployed, and the token address. Please refer to this site https://www.trufflesuite.com/docs/truffle/getting-started/running-migrations

Regards,
Alberto

**Comment by harodggg** [comment]
Thanks,  I know where i am wrong . Now, I have corrected. this is my
github:
https://github.com/harodggg/polkadot-hackthon/blob/main/deploy-erc20-moonbeam/READED.md
[image: migrate_erc20_truffle.png]


please check again, thank you very much

albertov19 <notifications@github.com> 于2020年10月26日周一 下午6:50写道：
